name: multistep
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python==3.8.5
  - pip
  - pip:
      alembic==1.4.1
      attrs==20.3.0
      azure-core==1.10.0
      azure-storage-blob==12.7.0
      backcall==0.2.0
      certifi==2020.12.5
      cffi==1.14.4
      chardet==4.0.0
      click==7.1.2
      cloudpickle==1.6.0
      colorama==0.4.4
      cryptography==3.3.1
      cycler==0.10.0
      databricks-cli==0.14.1
      decorator==4.4.2
      docker==4.4.1
      entrypoints==0.3
      Flask==1.1.2
      gitdb==4.0.5
      GitPython==3.1.12
      gunicorn==20.0.4
      idna==2.10
      iniconfig==1.1.1
      ipykernel==5.4.3
      ipython==7.19.0
      ipython-genutils==0.2.0
      isodate==0.6.0
      itsdangerous==1.1.0
      jedi==0.18.0
      Jinja2==2.11.2
      joblib==1.0.0
      jupyter-client==6.1.11
      jupyter-core==4.7.0
      kiwisolver==1.3.1
      lightgbm==3.1.1
      Mako==1.1.4
      MarkupSafe==1.1.1
      matplotlib==3.3.3
      mlflow==1.13.1
      msrest==0.6.19
      numpy==1.19.5
      oauthlib==3.1.0
      packaging==20.8
      pandas==1.2.0
      parso==0.8.1
      patsy==0.5.1
      pexpect==4.8.0
      pickleshare==0.7.5
      Pillow==8.1.0
      pluggy==0.13.1
      pretty-errors==1.2.19
      prometheus-client==0.9.0
      prometheus-flask-exporter==0.18.1
      prompt-toolkit==3.0.10
      protobuf==3.14.0
      ptyprocess==0.7.0
      py==1.10.0
      pycparser==2.20
      Pygments==2.7.4
      pyparsing==2.4.7
      pytest==6.2.1
      python-dateutil==2.8.1
      python-editor==1.0.4
      pytz==2020.5
      PyYAML==5.3.1
      pyzmq==21.0.1
      querystring-parser==1.2.4
      requests==2.25.1
      requests-oauthlib==1.3.0
      scikit-learn==0.24.0
      scipy==1.6.0
      six==1.15.0
      sklearn
      smmap==3.0.4
      SQLAlchemy==1.3.22
      sqlparse==0.4.1
      statsmodels==0.12.1
      tabulate==0.8.7
      threadpoolctl==2.1.0
      toml==0.10.2
      tornado==6.1
      tqdm==4.56.0
      traitlets==5.0.5
      urllib3==1.26.2
      verispy==0.1.12
      wcwidth==0.2.5
      websocket-client==0.57.0
      Werkzeug==1.0.1