apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.25.0 (a70f80cc)
  creationTimestamp: null
  labels:
    io.kompose.service: risk-assessment
  name: risk-assessment
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: risk-assessment
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.25.0 (a70f80cc)
      creationTimestamp: null
      labels:
        io.kompose.network/backend: "true"
        io.kompose.network/frontend: "true"
        io.kompose.service: risk-assessment
    spec:
      containers:
        - args:
            - bash
            - -c
            - chmod +x ./docker/launch.sh && ./docker/launch.sh
          image: risk-assessment
          name: risk-assessment
          ports:
            - containerPort: 5002
            - containerPort: 3005
          resources: {}
      hostname: risk-assessment
      restartPolicy: Always
status: {}
