apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: risk-assessment
  name: risk-assessment
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: risk-assessment
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: risk-assessment
    spec:
      containers:
      - image: risk-assessment
        imagePullPolicy: ""
        name: risk-assessment
        ports:
        - containerPort: 5002
        resources: {}
      hostname: risk_assessment
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
