"""empty message

Revision ID: 54a417a9f2d9
Revises: 
Create Date: 2022-01-20 15:25:18.773725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54a417a9f2d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('common_attack_pattern_enumeration_classification',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('capecId', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('abstraction', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('alternateTerms', sa.String(), nullable=True),
    sa.Column('likelihoodOfAttack', sa.String(), nullable=True),
    sa.Column('typicalSeverity', sa.String(), nullable=True),
    sa.Column('relatedAttackpatterns', sa.String(), nullable=True),
    sa.Column('executionFlow', sa.String(), nullable=True),
    sa.Column('prerequisites', sa.String(), nullable=True),
    sa.Column('skillsRequired', sa.String(), nullable=True),
    sa.Column('resourcesRequired', sa.String(), nullable=True),
    sa.Column('indicators', sa.String(), nullable=True),
    sa.Column('consequences', sa.String(), nullable=True),
    sa.Column('mitigations', sa.String(), nullable=True),
    sa.Column('exampleInstances', sa.String(), nullable=True),
    sa.Column('relatedWeaknesses', sa.String(), nullable=True),
    sa.Column('taxonomyMappings', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_common_attack_pattern_enumeration_classification_capecId'), 'common_attack_pattern_enumeration_classification', ['capecId'], unique=True)
    op.create_table('common_vulnerabilities_and_exposures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('CVEId', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('accessVector', sa.String(), nullable=True),
    sa.Column('accessComplexity', sa.String(), nullable=True),
    sa.Column('authentication', sa.String(), nullable=True),
    sa.Column('confidentialityImpact', sa.String(), nullable=True),
    sa.Column('integrityImpact', sa.String(), nullable=True),
    sa.Column('availabilityImpact', sa.String(), nullable=True),
    sa.Column('baseScore', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('exploitabilityScore', sa.Float(), nullable=True),
    sa.Column('impactScore', sa.Float(), nullable=True),
    sa.Column('obtainAllPrivilege', sa.Boolean(), nullable=True),
    sa.Column('obtainUserPrivilege', sa.Boolean(), nullable=True),
    sa.Column('obtainOtherPrivilege', sa.Boolean(), nullable=True),
    sa.Column('userInteractionRequired', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_common_vulnerabilities_and_exposures_CVEId'), 'common_vulnerabilities_and_exposures', ['CVEId'], unique=True)
    op.create_index(op.f('ix_common_vulnerabilities_and_exposures_description'), 'common_vulnerabilities_and_exposures', ['description'], unique=False)
    op.create_table('common_weakness_enumeration',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('CWEId', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('weakness', sa.String(), nullable=True),
    sa.Column('abstraction', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('extendedDescription', sa.String(), nullable=True),
    sa.Column('relatedWeaknesses', sa.String(), nullable=True),
    sa.Column('weaknessOrdinalities', sa.String(), nullable=True),
    sa.Column('applicablePlatforms', sa.String(), nullable=True),
    sa.Column('backgroundDetails', sa.String(), nullable=True),
    sa.Column('alternateTerms', sa.String(), nullable=True),
    sa.Column('modesOfIntroduction', sa.String(), nullable=True),
    sa.Column('exploitationFactors', sa.String(), nullable=True),
    sa.Column('likelihoodOfExploit', sa.String(), nullable=True),
    sa.Column('commonConsequences', sa.String(), nullable=True),
    sa.Column('detectionMethods', sa.String(), nullable=True),
    sa.Column('potentialMitigations', sa.String(), nullable=True),
    sa.Column('observedExamples', sa.String(), nullable=True),
    sa.Column('functionalAreas', sa.String(), nullable=True),
    sa.Column('affectedResources', sa.String(), nullable=True),
    sa.Column('taxonomyMappings', sa.String(), nullable=True),
    sa.Column('relatedAttackPatterns', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_common_weakness_enumeration_CWEId'), 'common_weakness_enumeration', ['CWEId'], unique=True)
    op.create_table('repo_actor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repo_asset_reputation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_hospital_id', sa.Integer(), nullable=True),
    sa.Column('global_asset_id', sa.Integer(), nullable=True),
    sa.Column('global_asset_type', sa.String(), nullable=True),
    sa.Column('global_asset_ip', sa.String(), nullable=True),
    sa.Column('first_update', sa.String(), nullable=True),
    sa.Column('last_update', sa.String(), nullable=True),
    sa.Column('asset_value', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('reputation', sa.Integer(), nullable=True),
    sa.Column('reputation_speed', sa.Integer(), nullable=True),
    sa.Column('weighted_importance', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repo_assets_variety',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repo_impact',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repo_net_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repo_objective',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repo_organisation_security_posture',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('q1_completedSRA', sa.Integer(), nullable=True),
    sa.Column('q2_include_IS_SRA', sa.Integer(), nullable=True),
    sa.Column('q3_compliance', sa.Integer(), nullable=True),
    sa.Column('q4_respond', sa.Integer(), nullable=True),
    sa.Column('q5_respond_personnel', sa.Integer(), nullable=True),
    sa.Column('q6_communicate_responses', sa.Integer(), nullable=True),
    sa.Column('q7_documented_policies', sa.Integer(), nullable=True),
    sa.Column('q8_reflect_business_practices', sa.Integer(), nullable=True),
    sa.Column('q9_documentation_availability', sa.Integer(), nullable=True),
    sa.Column('q10_responsible', sa.Integer(), nullable=True),
    sa.Column('q11_defined_access', sa.Integer(), nullable=True),
    sa.Column('q12_member_screening', sa.Integer(), nullable=True),
    sa.Column('q13_security_training', sa.Integer(), nullable=True),
    sa.Column('q14_monitoring_login', sa.Integer(), nullable=True),
    sa.Column('q15_protection_malicious', sa.Integer(), nullable=True),
    sa.Column('q16_password_security', sa.Integer(), nullable=True),
    sa.Column('q17_awareness_training', sa.Integer(), nullable=True),
    sa.Column('q18_sanction_policy', sa.Integer(), nullable=True),
    sa.Column('q19_personnel_access', sa.Integer(), nullable=True),
    sa.Column('q20_access_to_PHI', sa.Integer(), nullable=True),
    sa.Column('q21_kind_of_access', sa.Integer(), nullable=True),
    sa.Column('q22_use_of_encryption', sa.Integer(), nullable=True),
    sa.Column('q23_periodic_review_of_IS', sa.Integer(), nullable=True),
    sa.Column('q24_monitor_system_activity', sa.Integer(), nullable=True),
    sa.Column('q25_logoff_policy', sa.Integer(), nullable=True),
    sa.Column('q26_user_authentication_policy', sa.Integer(), nullable=True),
    sa.Column('q27_unauthorised_modification', sa.Integer(), nullable=True),
    sa.Column('q28_unauthorised_modification_transmitted', sa.Integer(), nullable=True),
    sa.Column('q29_manage_facility_access', sa.Integer(), nullable=True),
    sa.Column('q30_manage_device_access', sa.Integer(), nullable=True),
    sa.Column('q31_device_inventory', sa.Integer(), nullable=True),
    sa.Column('q32_validate_facility_access', sa.Integer(), nullable=True),
    sa.Column('q33_activity_on_IS_with_PHI', sa.Integer(), nullable=True),
    sa.Column('q34_backup_PHI', sa.Integer(), nullable=True),
    sa.Column('q35_sanitise_disposed_devices', sa.Integer(), nullable=True),
    sa.Column('q36_connected_devices', sa.Integer(), nullable=True),
    sa.Column('q37_necessary_access_rules', sa.Integer(), nullable=True),
    sa.Column('q38_monitor_3rd_access', sa.Integer(), nullable=True),
    sa.Column('q39_sanitise_new_devices', sa.Integer(), nullable=True),
    sa.Column('q40_BAA', sa.Integer(), nullable=True),
    sa.Column('q41_monitor_BA', sa.Integer(), nullable=True),
    sa.Column('q42_contingency_plan', sa.Integer(), nullable=True),
    sa.Column('q43_determine_critical_IS', sa.Integer(), nullable=True),
    sa.Column('q44_pdr_security_incidents', sa.Integer(), nullable=True),
    sa.Column('q45_incident_response_plan', sa.Integer(), nullable=True),
    sa.Column('q46_incident_response_team', sa.Integer(), nullable=True),
    sa.Column('q47_necessary_IS', sa.Integer(), nullable=True),
    sa.Column('q48_access_when_emergency', sa.Integer(), nullable=True),
    sa.Column('q49_backup_plan', sa.Integer(), nullable=True),
    sa.Column('q50_disaster_recovery_plan', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repo_service',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repo_utility',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vulnerability_report',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reportId', sa.String(), nullable=True),
    sa.Column('assessment_date', sa.String(), nullable=True),
    sa.Column('scan_start_time', sa.String(), nullable=True),
    sa.Column('scan_end_time', sa.String(), nullable=True),
    sa.Column('source_component', sa.Integer(), nullable=True),
    sa.Column('target_name', sa.String(), nullable=True),
    sa.Column('cvss_score', sa.String(), nullable=True),
    sa.Column('total_services', sa.String(), nullable=True),
    sa.Column('source_attackType', sa.String(), nullable=True),
    sa.Column('source_eventsCount', sa.String(), nullable=True),
    sa.Column('source_riskScore', sa.String(), nullable=True),
    sa.Column('source_severity', sa.String(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vulnerability_report_reportId'), 'vulnerability_report', ['reportId'], unique=True)
    op.create_table('repo_assets_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('daily_start_time', sa.DateTime(), nullable=True),
    sa.Column('daily_end_time', sa.DateTime(), nullable=True),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.Column('variety_fk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['variety_fk'], ['repo_assets_variety.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repo_objective_impact_relationship',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repo_objective_id', sa.Integer(), nullable=True),
    sa.Column('high_prob', sa.Integer(), nullable=True),
    sa.Column('med_prob', sa.Integer(), nullable=True),
    sa.Column('low_prob', sa.Integer(), nullable=True),
    sa.Column('impacts_state', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['repo_objective_id'], ['repo_objective.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repo_objective_repo_impact_association_table',
    sa.Column('repo_objective_id', sa.Integer(), nullable=True),
    sa.Column('repo_impact_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repo_impact_id'], ['repo_impact.id'], ),
    sa.ForeignKeyConstraint(['repo_objective_id'], ['repo_objective.id'], )
    )
    op.create_table('repo_objectives_options',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('objective_fk', sa.Integer(), nullable=False),
    sa.Column('alert_level', sa.Integer(), nullable=True),
    sa.Column('prob_likelihood', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['objective_fk'], ['repo_objective.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repo_service_repo_impact_association_table',
    sa.Column('repo_service_id', sa.Integer(), nullable=True),
    sa.Column('repo_impact_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repo_impact_id'], ['repo_impact.id'], ),
    sa.ForeignKeyConstraint(['repo_service_id'], ['repo_service.id'], )
    )
    op.create_table('repo_threat',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('CAPEC_id', sa.Integer(), nullable=True),
    sa.Column('prob', sa.Integer(), nullable=True),
    sa.Column('user_prob', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['CAPEC_id'], ['common_attack_pattern_enumeration_classification.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repo_utility_objective_relationship',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repo_utility_id', sa.Integer(), nullable=True),
    sa.Column('utility_value', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repo_utility_id'], ['repo_utility.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repo_utility_repo_objective_association_table',
    sa.Column('repo_utility_id', sa.Integer(), nullable=True),
    sa.Column('repo_objective_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repo_objective_id'], ['repo_objective.id'], ),
    sa.ForeignKeyConstraint(['repo_utility_id'], ['repo_utility.id'], )
    )
    op.create_table('vulnerabilities_weakness_link',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cve_id', sa.Integer(), nullable=False),
    sa.Column('cwe_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cve_id'], ['common_vulnerabilities_and_exposures.id'], ),
    sa.ForeignKeyConstraint(['cwe_id'], ['common_weakness_enumeration.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repo_asset',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('common_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('mac_address', sa.String(), nullable=True),
    sa.Column('has_static_ip', sa.Boolean(), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('net_group_fk', sa.Integer(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('loss_of_revenue', sa.Integer(), nullable=True),
    sa.Column('additional_expenses', sa.Integer(), nullable=True),
    sa.Column('security_levels', sa.Integer(), nullable=True),
    sa.Column('customer_service', sa.Integer(), nullable=True),
    sa.Column('operating_zone', sa.Integer(), nullable=True),
    sa.Column('last_touch_date', sa.DateTime(), nullable=True),
    sa.Column('type_fk', sa.Integer(), nullable=True),
    sa.Column('integrity', sa.Integer(), nullable=True),
    sa.Column('availability', sa.Integer(), nullable=True),
    sa.Column('confidentiality', sa.Integer(), nullable=True),
    sa.Column('current_status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['net_group_fk'], ['repo_net_group.id'], ),
    sa.ForeignKeyConstraint(['owner'], ['repo_actor.id'], ),
    sa.ForeignKeyConstraint(['type_fk'], ['repo_assets_type.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['repo_actor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repo_materialisation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('threat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['threat_id'], ['repo_threat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repo_objective_impact_relationship_impact_many_to_many',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repo_this_entry_id', sa.Integer(), nullable=True),
    sa.Column('repo_impact_id', sa.Integer(), nullable=True),
    sa.Column('repo_impact_state', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repo_impact_id'], ['repo_impact.id'], ),
    sa.ForeignKeyConstraint(['repo_this_entry_id'], ['repo_objective_impact_relationship.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repo_response',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('threat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['threat_id'], ['repo_threat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repo_threat_common_vulnerabilities_and_exposures_association_table',
    sa.Column('repo_threat_id', sa.Integer(), nullable=True),
    sa.Column('common_vulnerabilities_and_exposures_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['common_vulnerabilities_and_exposures_id'], ['common_vulnerabilities_and_exposures.id'], ),
    sa.ForeignKeyConstraint(['repo_threat_id'], ['repo_threat.id'], )
    )
    op.create_table('repo_utility_objective_relationship_many_to_many',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repo_this_entry_id', sa.Integer(), nullable=True),
    sa.Column('repo_objective_id', sa.Integer(), nullable=True),
    sa.Column('repo_objective_state', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repo_objective_id'], ['repo_objective.id'], ),
    sa.ForeignKeyConstraint(['repo_this_entry_id'], ['repo_utility_objective_relationship.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repo_asset_common_vulnerabilities_and_exposures_association_table',
    sa.Column('repo_asset_id', sa.Integer(), nullable=True),
    sa.Column('common_vulnerabilities_and_exposures_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['common_vulnerabilities_and_exposures_id'], ['common_vulnerabilities_and_exposures.id'], ),
    sa.ForeignKeyConstraint(['repo_asset_id'], ['repo_asset.id'], )
    )
    op.create_table('repo_asset_repo_service_association_table',
    sa.Column('repo_asset_id', sa.Integer(), nullable=True),
    sa.Column('repo_service_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repo_asset_id'], ['repo_asset.id'], ),
    sa.ForeignKeyConstraint(['repo_service_id'], ['repo_service.id'], )
    )
    op.create_table('repo_asset_repo_threat_relationship',
    sa.Column('repo_asset_id', sa.Integer(), nullable=False),
    sa.Column('repo_threat_id', sa.Integer(), nullable=False),
    sa.Column('risk_skill_level', sa.Integer(), nullable=True),
    sa.Column('risk_motive', sa.Integer(), nullable=True),
    sa.Column('risk_source', sa.Integer(), nullable=True),
    sa.Column('risk_actor', sa.Integer(), nullable=True),
    sa.Column('risk_opportunity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repo_asset_id'], ['repo_asset.id'], ),
    sa.ForeignKeyConstraint(['repo_threat_id'], ['repo_threat.id'], ),
    sa.PrimaryKeyConstraint('repo_asset_id', 'repo_threat_id')
    )
    op.create_table('repo_asset_service',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('vreport_id', sa.Integer(), nullable=True),
    sa.Column('port', sa.String(), nullable=True),
    sa.Column('protocol', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('service_name', sa.String(), nullable=True),
    sa.Column('service_product', sa.String(), nullable=True),
    sa.Column('service_product_version', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['repo_asset.id'], ),
    sa.ForeignKeyConstraint(['vreport_id'], ['vulnerability_report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repo_asset_threat_consequence_service_impact_relationship',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repo_asset_id', sa.Integer(), nullable=True),
    sa.Column('repo_threat_id', sa.Integer(), nullable=True),
    sa.Column('repo_impact_id', sa.Integer(), nullable=True),
    sa.Column('high_prob', sa.Integer(), nullable=True),
    sa.Column('med_prob', sa.Integer(), nullable=True),
    sa.Column('low_prob', sa.Integer(), nullable=True),
    sa.Column('consequences_state', sa.String(), nullable=True),
    sa.Column('services_state', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['repo_asset_id'], ['repo_asset.id'], ),
    sa.ForeignKeyConstraint(['repo_impact_id'], ['repo_impact.id'], ),
    sa.ForeignKeyConstraint(['repo_threat_id'], ['repo_threat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repo_consequence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('threat_id', sa.Integer(), nullable=True),
    sa.Column('materialisation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['materialisation_id'], ['repo_materialisation.id'], ),
    sa.ForeignKeyConstraint(['threat_id'], ['repo_threat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repo_risk_assessment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repo_threat_id', sa.Integer(), nullable=True),
    sa.Column('repo_asset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repo_asset_id'], ['repo_asset.id'], ),
    sa.ForeignKeyConstraint(['repo_threat_id'], ['repo_threat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repo_risk_threat_asset_materialisation',
    sa.Column('repo_asset_id', sa.Integer(), nullable=False),
    sa.Column('repo_threat_id', sa.Integer(), nullable=False),
    sa.Column('repo_response_id', sa.Integer(), nullable=False),
    sa.Column('repo_materialisation_id', sa.Integer(), nullable=False),
    sa.Column('threat_occurrence', sa.Boolean(), nullable=False),
    sa.Column('prob', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repo_asset_id'], ['repo_asset.id'], ),
    sa.ForeignKeyConstraint(['repo_materialisation_id'], ['repo_materialisation.id'], ),
    sa.ForeignKeyConstraint(['repo_response_id'], ['repo_response.id'], ),
    sa.ForeignKeyConstraint(['repo_threat_id'], ['repo_threat.id'], ),
    sa.PrimaryKeyConstraint('repo_asset_id', 'repo_threat_id', 'repo_response_id', 'repo_materialisation_id', 'threat_occurrence')
    )
    op.create_table('vulnerability_report_vulnerabilities_link',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vreport_id', sa.Integer(), nullable=False),
    sa.Column('cve_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('VReport_assetID', sa.String(), nullable=True),
    sa.Column('VReport_assetIp', sa.String(), nullable=True),
    sa.Column('VReport_port', sa.String(), nullable=True),
    sa.Column('VReport_CVSS_score', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('comments', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['repo_asset.id'], ),
    sa.ForeignKeyConstraint(['cve_id'], ['common_vulnerabilities_and_exposures.id'], ),
    sa.ForeignKeyConstraint(['vreport_id'], ['vulnerability_report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repo_asset_threat_consequence_service_impact_relationship_consequence_many_to_many',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repo_this_entry_id', sa.Integer(), nullable=True),
    sa.Column('repo_consequence_id', sa.Integer(), nullable=True),
    sa.Column('repo_consequence_state', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['repo_consequence_id'], ['repo_consequence.id'], ),
    sa.ForeignKeyConstraint(['repo_this_entry_id'], ['repo_asset_threat_consequence_service_impact_relationship.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repo_asset_threat_consequence_service_impact_relationship_service_many_to_many',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repo_this_entry_id', sa.Integer(), nullable=True),
    sa.Column('repo_service_id', sa.Integer(), nullable=True),
    sa.Column('repo_service_state', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['repo_service_id'], ['repo_service.id'], ),
    sa.ForeignKeyConstraint(['repo_this_entry_id'], ['repo_asset_threat_consequence_service_impact_relationship.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repo_consequence_repo_impact_association_table',
    sa.Column('repo_consequence_id', sa.Integer(), nullable=True),
    sa.Column('repo_impact_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repo_consequence_id'], ['repo_consequence.id'], ),
    sa.ForeignKeyConstraint(['repo_impact_id'], ['repo_impact.id'], )
    )
    op.create_table('repo_control',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('vulnerability_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vulnerability_id'], ['vulnerability_report_vulnerabilities_link.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repo_risk_assessment_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('risk_assessment_id', sa.Integer(), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('exposure_set', sa.String(), nullable=True),
    sa.Column('responses_set', sa.String(), nullable=True),
    sa.Column('materialisations_set', sa.String(), nullable=True),
    sa.Column('consequences_set', sa.String(), nullable=True),
    sa.Column('services_set', sa.String(), nullable=True),
    sa.Column('impacts_set', sa.String(), nullable=True),
    sa.Column('objectives_set', sa.String(), nullable=True),
    sa.Column('exposure_inference', sa.String(), nullable=True),
    sa.Column('responses_inference', sa.String(), nullable=True),
    sa.Column('materialisations_inference', sa.String(), nullable=True),
    sa.Column('consequences_inference', sa.String(), nullable=True),
    sa.Column('services_inference', sa.String(), nullable=True),
    sa.Column('impacts_inference', sa.String(), nullable=True),
    sa.Column('objectives_inference', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['risk_assessment_id'], ['repo_risk_assessment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repo_risk_threat_asset_consequence',
    sa.Column('repo_asset_id', sa.Integer(), nullable=False),
    sa.Column('repo_threat_id', sa.Integer(), nullable=False),
    sa.Column('repo_response_id', sa.Integer(), nullable=False),
    sa.Column('repo_consequence_id', sa.Integer(), nullable=False),
    sa.Column('threat_occurrence', sa.Boolean(), nullable=False),
    sa.Column('prob', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repo_asset_id'], ['repo_asset.id'], ),
    sa.ForeignKeyConstraint(['repo_consequence_id'], ['repo_consequence.id'], ),
    sa.ForeignKeyConstraint(['repo_response_id'], ['repo_response.id'], ),
    sa.ForeignKeyConstraint(['repo_threat_id'], ['repo_threat.id'], ),
    sa.PrimaryKeyConstraint('repo_asset_id', 'repo_threat_id', 'repo_response_id', 'repo_consequence_id', 'threat_occurrence')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repo_risk_threat_asset_consequence')
    op.drop_table('repo_risk_assessment_reports')
    op.drop_table('repo_control')
    op.drop_table('repo_consequence_repo_impact_association_table')
    op.drop_table('repo_asset_threat_consequence_service_impact_relationship_service_many_to_many')
    op.drop_table('repo_asset_threat_consequence_service_impact_relationship_consequence_many_to_many')
    op.drop_table('vulnerability_report_vulnerabilities_link')
    op.drop_table('repo_risk_threat_asset_materialisation')
    op.drop_table('repo_risk_assessment')
    op.drop_table('repo_consequence')
    op.drop_table('repo_asset_threat_consequence_service_impact_relationship')
    op.drop_table('repo_asset_service')
    op.drop_table('repo_asset_repo_threat_relationship')
    op.drop_table('repo_asset_repo_service_association_table')
    op.drop_table('repo_asset_common_vulnerabilities_and_exposures_association_table')
    op.drop_table('repo_utility_objective_relationship_many_to_many')
    op.drop_table('repo_threat_common_vulnerabilities_and_exposures_association_table')
    op.drop_table('repo_response')
    op.drop_table('repo_objective_impact_relationship_impact_many_to_many')
    op.drop_table('repo_materialisation')
    op.drop_table('repo_asset')
    op.drop_table('vulnerabilities_weakness_link')
    op.drop_table('repo_utility_repo_objective_association_table')
    op.drop_table('repo_utility_objective_relationship')
    op.drop_table('repo_threat')
    op.drop_table('repo_service_repo_impact_association_table')
    op.drop_table('repo_objectives_options')
    op.drop_table('repo_objective_repo_impact_association_table')
    op.drop_table('repo_objective_impact_relationship')
    op.drop_table('repo_assets_type')
    op.drop_index(op.f('ix_vulnerability_report_reportId'), table_name='vulnerability_report')
    op.drop_table('vulnerability_report')
    op.drop_table('repo_utility')
    op.drop_table('repo_service')
    op.drop_table('repo_organisation_security_posture')
    op.drop_table('repo_objective')
    op.drop_table('repo_net_group')
    op.drop_table('repo_impact')
    op.drop_table('repo_assets_variety')
    op.drop_table('repo_asset_reputation')
    op.drop_table('repo_actor')
    op.drop_index(op.f('ix_common_weakness_enumeration_CWEId'), table_name='common_weakness_enumeration')
    op.drop_table('common_weakness_enumeration')
    op.drop_index(op.f('ix_common_vulnerabilities_and_exposures_description'), table_name='common_vulnerabilities_and_exposures')
    op.drop_index(op.f('ix_common_vulnerabilities_and_exposures_CVEId'), table_name='common_vulnerabilities_and_exposures')
    op.drop_table('common_vulnerabilities_and_exposures')
    op.drop_index(op.f('ix_common_attack_pattern_enumeration_classification_capecId'), table_name='common_attack_pattern_enumeration_classification')
    op.drop_table('common_attack_pattern_enumeration_classification')
    # ### end Alembic commands ###
