"""empty message

Revision ID: 591159f19062
Revises: 5e0200332209
Create Date: 2022-02-09 17:56:17.862305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '591159f19062'
down_revision = '5e0200332209'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repo_objectives_options', sa.Column('objective_level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repo_objectives_options', 'objective_level')
    # ### end Alembic commands ###
