"""empty message

Revision ID: 5e0200332209
Revises: 54a417a9f2d9
Create Date: 2022-02-09 17:10:43.633167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e0200332209'
down_revision = '54a417a9f2d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repo_control', sa.Column('effectiveness', sa.Integer(), nullable=True))
    op.add_column('repo_risk_assessment_reports', sa.Column('alerts_triggered', sa.String(), nullable=True))
    op.add_column('repo_risk_assessment_reports', sa.Column('utilities_inference', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repo_risk_assessment_reports', 'utilities_inference')
    op.drop_column('repo_risk_assessment_reports', 'alerts_triggered')
    op.drop_column('repo_control', 'effectiveness')
    # ### end Alembic commands ###
