"""empty message

Revision ID: 851a00be1703
Revises: 
Create Date: 2020-03-09 16:47:43.128319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '851a00be1703'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CAPEC',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capecId', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('abstraction', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('alternateTerms', sa.String(), nullable=True),
    sa.Column('likelihoodOfAttack', sa.String(), nullable=True),
    sa.Column('typicalSeverity', sa.String(), nullable=True),
    sa.Column('relatedAttack', sa.String(), nullable=True),
    sa.Column('patterns', sa.String(), nullable=True),
    sa.Column('executionFlow', sa.String(), nullable=True),
    sa.Column('prerequisites', sa.String(), nullable=True),
    sa.Column('skillsRequired', sa.String(), nullable=True),
    sa.Column('resourcesRequired', sa.String(), nullable=True),
    sa.Column('indicators', sa.String(), nullable=True),
    sa.Column('consequences', sa.String(), nullable=True),
    sa.Column('mitigations', sa.String(), nullable=True),
    sa.Column('exampleInstances', sa.String(), nullable=True),
    sa.Column('relatedWeaknesses', sa.String(), nullable=True),
    sa.Column('taxonomyMappings', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_CAPEC_capecId'), 'CAPEC', ['capecId'], unique=True)
    op.create_table('CVE',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('CVEId', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('references', sa.String(), nullable=True),
    sa.Column('phase', sa.String(), nullable=True),
    sa.Column('votes', sa.String(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_CVE_CVEId'), 'CVE', ['CVEId'], unique=True)
    op.create_index(op.f('ix_CVE_status'), 'CVE', ['status'], unique=False)
    op.create_table('CWE',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('CWEId', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('weakness', sa.String(), nullable=True),
    sa.Column('abstraction', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('extendedDescription', sa.String(), nullable=True),
    sa.Column('relatedWeaknesses', sa.String(), nullable=True),
    sa.Column('weaknessOrdinalities', sa.String(), nullable=True),
    sa.Column('applicablePlatforms', sa.String(), nullable=True),
    sa.Column('backgroundDetails', sa.String(), nullable=True),
    sa.Column('alternateTerms', sa.String(), nullable=True),
    sa.Column('modesOfIntroduction', sa.String(), nullable=True),
    sa.Column('exploitationFactors', sa.String(), nullable=True),
    sa.Column('likelihoodOfExploit', sa.String(), nullable=True),
    sa.Column('commonConsequences', sa.String(), nullable=True),
    sa.Column('detectionMethods', sa.String(), nullable=True),
    sa.Column('potentialMitigations', sa.String(), nullable=True),
    sa.Column('observedExamples', sa.String(), nullable=True),
    sa.Column('functionalAreas', sa.String(), nullable=True),
    sa.Column('affectedResources', sa.String(), nullable=True),
    sa.Column('taxonomyMappings', sa.String(), nullable=True),
    sa.Column('relatedAttackPatterns', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_CWE_CWEId'), 'CWE', ['CWEId'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_CWE_CWEId'), table_name='CWE')
    op.drop_table('CWE')
    op.drop_index(op.f('ix_CVE_status'), table_name='CVE')
    op.drop_index(op.f('ix_CVE_CVEId'), table_name='CVE')
    op.drop_table('CVE')
    op.drop_index(op.f('ix_CAPEC_capecId'), table_name='CAPEC')
    op.drop_table('CAPEC')
    # ### end Alembic commands ###
