"""empty message

Revision ID: b3403fa9cdc8
Revises: ece65fd09234
Create Date: 2020-03-06 19:46:38.430446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3403fa9cdc8'
down_revision = 'ece65fd09234'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CVE',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('CVEId', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('references', sa.String(), nullable=True),
    sa.Column('phase', sa.String(), nullable=True),
    sa.Column('votes', sa.String(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_CVE_CVEId'), 'CVE', ['CVEId'], unique=True)
    op.create_index(op.f('ix_CVE_status'), 'CVE', ['status'], unique=False)
    op.create_table('CWE',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('CWEId', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('weakness', sa.String(), nullable=True),
    sa.Column('abstraction', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('extendedDescription', sa.String(), nullable=True),
    sa.Column('relatedWeaknesses', sa.String(), nullable=True),
    sa.Column('weaknessOrdinalities', sa.String(), nullable=True),
    sa.Column('applicablePlatforms', sa.String(), nullable=True),
    sa.Column('backgroundDetails', sa.String(), nullable=True),
    sa.Column('alternateTerms', sa.String(), nullable=True),
    sa.Column('modesOfIntroduction', sa.String(), nullable=True),
    sa.Column('exploitationFactors', sa.String(), nullable=True),
    sa.Column('likelihoodOfExploit', sa.String(), nullable=True),
    sa.Column('commonConsequences', sa.String(), nullable=True),
    sa.Column('detectionMethods', sa.String(), nullable=True),
    sa.Column('potentialMitigations', sa.String(), nullable=True),
    sa.Column('observedExamples', sa.String(), nullable=True),
    sa.Column('functionalAreas', sa.String(), nullable=True),
    sa.Column('affectedResources', sa.String(), nullable=True),
    sa.Column('taxonomyMappings', sa.String(), nullable=True),
    sa.Column('relatedAttackPatterns', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_CWE_CWEId'), 'CWE', ['CWEId'], unique=True)
    op.drop_index('ix_post_timestamp', table_name='post')
    op.drop_table('post')
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_username', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_username', 'user', ['username'], unique=1)
    op.create_index('ix_user_email', 'user', ['email'], unique=1)
    op.create_table('post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.VARCHAR(length=140), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_post_timestamp', 'post', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_CWE_CWEId'), table_name='CWE')
    op.drop_table('CWE')
    op.drop_index(op.f('ix_CVE_status'), table_name='CVE')
    op.drop_index(op.f('ix_CVE_CVEId'), table_name='CVE')
    op.drop_table('CVE')
    # ### end Alembic commands ###
