"""empty message

Revision ID: d36529ff253a
Revises: 
Create Date: 2021-10-27 11:18:29.294715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd36529ff253a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('common_attack_pattern_enumeration_classification',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('capecId', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('abstraction', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('alternateTerms', sa.String(), nullable=True),
    sa.Column('likelihoodOfAttack', sa.String(), nullable=True),
    sa.Column('typicalSeverity', sa.String(), nullable=True),
    sa.Column('relatedAttackpatterns', sa.String(), nullable=True),
    sa.Column('executionFlow', sa.String(), nullable=True),
    sa.Column('prerequisites', sa.String(), nullable=True),
    sa.Column('skillsRequired', sa.String(), nullable=True),
    sa.Column('resourcesRequired', sa.String(), nullable=True),
    sa.Column('indicators', sa.String(), nullable=True),
    sa.Column('consequences', sa.String(), nullable=True),
    sa.Column('mitigations', sa.String(), nullable=True),
    sa.Column('exampleInstances', sa.String(), nullable=True),
    sa.Column('relatedWeaknesses', sa.String(), nullable=True),
    sa.Column('taxonomyMappings', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_common_attack_pattern_enumeration_classification_capecId'), 'common_attack_pattern_enumeration_classification', ['capecId'], unique=True)
    op.create_table('common_vulnerabilities_and_exposures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('CVEId', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('accessVector', sa.String(), nullable=True),
    sa.Column('accessComplexity', sa.String(), nullable=True),
    sa.Column('authentication', sa.String(), nullable=True),
    sa.Column('confidentialityImpact', sa.String(), nullable=True),
    sa.Column('integrityImpact', sa.String(), nullable=True),
    sa.Column('availabilityImpact', sa.String(), nullable=True),
    sa.Column('baseScore', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('exploitabilityScore', sa.Float(), nullable=True),
    sa.Column('impactScore', sa.Float(), nullable=True),
    sa.Column('obtainAllPrivilege', sa.Boolean(), nullable=True),
    sa.Column('obtainUserPrivilege', sa.Boolean(), nullable=True),
    sa.Column('obtainOtherPrivilege', sa.Boolean(), nullable=True),
    sa.Column('userInteractionRequired', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_common_vulnerabilities_and_exposures_CVEId'), 'common_vulnerabilities_and_exposures', ['CVEId'], unique=True)
    op.create_index(op.f('ix_common_vulnerabilities_and_exposures_description'), 'common_vulnerabilities_and_exposures', ['description'], unique=False)
    op.create_table('common_weakness_enumeration',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('CWEId', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('weakness', sa.String(), nullable=True),
    sa.Column('abstraction', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('extendedDescription', sa.String(), nullable=True),
    sa.Column('relatedWeaknesses', sa.String(), nullable=True),
    sa.Column('weaknessOrdinalities', sa.String(), nullable=True),
    sa.Column('applicablePlatforms', sa.String(), nullable=True),
    sa.Column('backgroundDetails', sa.String(), nullable=True),
    sa.Column('alternateTerms', sa.String(), nullable=True),
    sa.Column('modesOfIntroduction', sa.String(), nullable=True),
    sa.Column('exploitationFactors', sa.String(), nullable=True),
    sa.Column('likelihoodOfExploit', sa.String(), nullable=True),
    sa.Column('commonConsequences', sa.String(), nullable=True),
    sa.Column('detectionMethods', sa.String(), nullable=True),
    sa.Column('potentialMitigations', sa.String(), nullable=True),
    sa.Column('observedExamples', sa.String(), nullable=True),
    sa.Column('functionalAreas', sa.String(), nullable=True),
    sa.Column('affectedResources', sa.String(), nullable=True),
    sa.Column('taxonomyMappings', sa.String(), nullable=True),
    sa.Column('relatedAttackPatterns', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_common_weakness_enumeration_CWEId'), 'common_weakness_enumeration', ['CWEId'], unique=True)
    op.create_table('repo_actor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repo_asset_reputation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_hospital_id', sa.Integer(), nullable=True),
    sa.Column('global_asset_id', sa.Integer(), nullable=True),
    sa.Column('global_asset_type', sa.String(), nullable=True),
    sa.Column('global_asset_ip', sa.String(), nullable=True),
    sa.Column('first_update', sa.String(), nullable=True),
    sa.Column('last_update', sa.String(), nullable=True),
    sa.Column('asset_value', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('reputation', sa.Integer(), nullable=True),
    sa.Column('reputation_speed', sa.Integer(), nullable=True),
    sa.Column('weighted_importance', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repo_assets_type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repo_impact',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repo_net_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repo_objective',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repo_service',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repo_utility',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vulnerability_report',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reportId', sa.String(), nullable=True),
    sa.Column('scan_start_time', sa.String(), nullable=True),
    sa.Column('scan_end_time', sa.String(), nullable=True),
    sa.Column('target_name', sa.String(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vulnerability_report_reportId'), 'vulnerability_report', ['reportId'], unique=True)
    op.create_table('repo_asset',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('owner', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('mac_address', sa.String(), nullable=True),
    sa.Column('has_static_ip', sa.Boolean(), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('net_group_fk', sa.Integer(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('loss_of_revenue', sa.Integer(), nullable=True),
    sa.Column('additional_expenses', sa.Integer(), nullable=True),
    sa.Column('regulatory_legal', sa.Integer(), nullable=True),
    sa.Column('customer_service', sa.Integer(), nullable=True),
    sa.Column('goodwill', sa.Integer(), nullable=True),
    sa.Column('last_touch_date', sa.DateTime(), nullable=True),
    sa.Column('type_fk', sa.Integer(), nullable=True),
    sa.Column('integrity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['net_group_fk'], ['repo_net_group.id'], ),
    sa.ForeignKeyConstraint(['owner'], ['repo_actor.id'], ),
    sa.ForeignKeyConstraint(['type_fk'], ['repo_assets_type.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['repo_actor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repo_objective_impact_relationship',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repo_objective_id', sa.Integer(), nullable=True),
    sa.Column('high_prob', sa.Integer(), nullable=True),
    sa.Column('med_prob', sa.Integer(), nullable=True),
    sa.Column('low_prob', sa.Integer(), nullable=True),
    sa.Column('impacts_state', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['repo_objective_id'], ['repo_objective.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repo_objective_repo_impact_association_table',
    sa.Column('repo_objective_id', sa.Integer(), nullable=True),
    sa.Column('repo_impact_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repo_impact_id'], ['repo_impact.id'], ),
    sa.ForeignKeyConstraint(['repo_objective_id'], ['repo_objective.id'], )
    )
    op.create_table('repo_objectives_options',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('objective_fk', sa.Integer(), nullable=False),
    sa.Column('alert_level', sa.Integer(), nullable=True),
    sa.Column('prob_likelihood', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['objective_fk'], ['repo_objective.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repo_service_repo_impact_association_table',
    sa.Column('repo_service_id', sa.Integer(), nullable=True),
    sa.Column('repo_impact_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repo_impact_id'], ['repo_impact.id'], ),
    sa.ForeignKeyConstraint(['repo_service_id'], ['repo_service.id'], )
    )
    op.create_table('repo_threat',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('CAPEC_id', sa.Integer(), nullable=True),
    sa.Column('prob', sa.Integer(), nullable=True),
    sa.Column('user_prob', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['CAPEC_id'], ['common_attack_pattern_enumeration_classification.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repo_utility_objective_relationship',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repo_utility_id', sa.Integer(), nullable=True),
    sa.Column('utility_value', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repo_utility_id'], ['repo_utility.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repo_utility_repo_objective_association_table',
    sa.Column('repo_utility_id', sa.Integer(), nullable=True),
    sa.Column('repo_objective_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repo_objective_id'], ['repo_objective.id'], ),
    sa.ForeignKeyConstraint(['repo_utility_id'], ['repo_utility.id'], )
    )
    op.create_table('vulnerabilities_weakness_link',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cve_id', sa.Integer(), nullable=False),
    sa.Column('cwe_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cve_id'], ['common_vulnerabilities_and_exposures.id'], ),
    sa.ForeignKeyConstraint(['cwe_id'], ['common_weakness_enumeration.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repo_asset_repo_service_association_table',
    sa.Column('repo_asset_id', sa.Integer(), nullable=True),
    sa.Column('repo_service_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repo_asset_id'], ['repo_asset.id'], ),
    sa.ForeignKeyConstraint(['repo_service_id'], ['repo_service.id'], )
    )
    op.create_table('repo_asset_repo_threat_relationship',
    sa.Column('repo_asset_id', sa.Integer(), nullable=False),
    sa.Column('repo_threat_id', sa.Integer(), nullable=False),
    sa.Column('risk_skill_level', sa.Integer(), nullable=True),
    sa.Column('risk_motive', sa.Integer(), nullable=True),
    sa.Column('risk_source', sa.Integer(), nullable=True),
    sa.Column('risk_actor', sa.Integer(), nullable=True),
    sa.Column('risk_opportunity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repo_asset_id'], ['repo_asset.id'], ),
    sa.ForeignKeyConstraint(['repo_threat_id'], ['repo_threat.id'], ),
    sa.PrimaryKeyConstraint('repo_asset_id', 'repo_threat_id')
    )
    op.create_table('repo_asset_threat_consequence_service_impact_relationship',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repo_asset_id', sa.Integer(), nullable=True),
    sa.Column('repo_threat_id', sa.Integer(), nullable=True),
    sa.Column('repo_impact_id', sa.Integer(), nullable=True),
    sa.Column('high_prob', sa.Integer(), nullable=True),
    sa.Column('med_prob', sa.Integer(), nullable=True),
    sa.Column('low_prob', sa.Integer(), nullable=True),
    sa.Column('consequences_state', sa.String(), nullable=True),
    sa.Column('services_state', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['repo_asset_id'], ['repo_asset.id'], ),
    sa.ForeignKeyConstraint(['repo_impact_id'], ['repo_impact.id'], ),
    sa.ForeignKeyConstraint(['repo_threat_id'], ['repo_threat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repo_materialisation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('threat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['threat_id'], ['repo_threat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repo_objective_impact_relationship_impact_many_to_many',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repo_this_entry_id', sa.Integer(), nullable=True),
    sa.Column('repo_impact_id', sa.Integer(), nullable=True),
    sa.Column('repo_impact_state', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repo_impact_id'], ['repo_impact.id'], ),
    sa.ForeignKeyConstraint(['repo_this_entry_id'], ['repo_objective_impact_relationship.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repo_response',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('threat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['threat_id'], ['repo_threat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repo_risk_assessment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repo_threat_id', sa.Integer(), nullable=True),
    sa.Column('repo_asset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repo_asset_id'], ['repo_asset.id'], ),
    sa.ForeignKeyConstraint(['repo_threat_id'], ['repo_threat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repo_utility_objective_relationship_many_to_many',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repo_this_entry_id', sa.Integer(), nullable=True),
    sa.Column('repo_objective_id', sa.Integer(), nullable=True),
    sa.Column('repo_objective_state', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repo_objective_id'], ['repo_objective.id'], ),
    sa.ForeignKeyConstraint(['repo_this_entry_id'], ['repo_utility_objective_relationship.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vulnerability_report_vulnerabilities_link',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vreport_id', sa.Integer(), nullable=False),
    sa.Column('cve_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('VReport_assetID', sa.String(), nullable=True),
    sa.Column('VReport_assetIp', sa.String(), nullable=True),
    sa.Column('VReport_port', sa.String(), nullable=True),
    sa.Column('VReport_CVSS_score', sa.String(), nullable=True),
    sa.Column('comments', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['repo_asset.id'], ),
    sa.ForeignKeyConstraint(['cve_id'], ['common_vulnerabilities_and_exposures.id'], ),
    sa.ForeignKeyConstraint(['vreport_id'], ['vulnerability_report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repo_asset_threat_consequence_service_impact_relationship_service_many_to_many',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repo_this_entry_id', sa.Integer(), nullable=True),
    sa.Column('repo_service_id', sa.Integer(), nullable=True),
    sa.Column('repo_service_state', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['repo_service_id'], ['repo_service.id'], ),
    sa.ForeignKeyConstraint(['repo_this_entry_id'], ['repo_asset_threat_consequence_service_impact_relationship.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repo_consequence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('threat_id', sa.Integer(), nullable=True),
    sa.Column('materialisation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['materialisation_id'], ['repo_materialisation.id'], ),
    sa.ForeignKeyConstraint(['threat_id'], ['repo_threat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repo_control',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('vulnerability_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vulnerability_id'], ['vulnerability_report_vulnerabilities_link.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repo_risk_assessment_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('risk_assessment_id', sa.Integer(), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('exposure_set', sa.String(), nullable=True),
    sa.Column('responses_set', sa.String(), nullable=True),
    sa.Column('materialisations_set', sa.String(), nullable=True),
    sa.Column('consequences_set', sa.String(), nullable=True),
    sa.Column('services_set', sa.String(), nullable=True),
    sa.Column('impacts_set', sa.String(), nullable=True),
    sa.Column('objectives_set', sa.String(), nullable=True),
    sa.Column('exposure_inference', sa.String(), nullable=True),
    sa.Column('responses_inference', sa.String(), nullable=True),
    sa.Column('materialisations_inference', sa.String(), nullable=True),
    sa.Column('consequences_inference', sa.String(), nullable=True),
    sa.Column('services_inference', sa.String(), nullable=True),
    sa.Column('impacts_inference', sa.String(), nullable=True),
    sa.Column('objectives_inference', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['risk_assessment_id'], ['repo_risk_assessment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repo_risk_threat_asset_materialisation',
    sa.Column('repo_asset_id', sa.Integer(), nullable=False),
    sa.Column('repo_threat_id', sa.Integer(), nullable=False),
    sa.Column('repo_response_id', sa.Integer(), nullable=False),
    sa.Column('repo_materialisation_id', sa.Integer(), nullable=False),
    sa.Column('threat_occurrence', sa.Boolean(), nullable=False),
    sa.Column('prob', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repo_asset_id'], ['repo_asset.id'], ),
    sa.ForeignKeyConstraint(['repo_materialisation_id'], ['repo_materialisation.id'], ),
    sa.ForeignKeyConstraint(['repo_response_id'], ['repo_response.id'], ),
    sa.ForeignKeyConstraint(['repo_threat_id'], ['repo_threat.id'], ),
    sa.PrimaryKeyConstraint('repo_asset_id', 'repo_threat_id', 'repo_response_id', 'repo_materialisation_id', 'threat_occurrence')
    )
    op.create_table('repo_asset_threat_consequence_service_impact_relationship_consequence_many_to_many',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repo_this_entry_id', sa.Integer(), nullable=True),
    sa.Column('repo_consequence_id', sa.Integer(), nullable=True),
    sa.Column('repo_consequence_state', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['repo_consequence_id'], ['repo_consequence.id'], ),
    sa.ForeignKeyConstraint(['repo_this_entry_id'], ['repo_asset_threat_consequence_service_impact_relationship.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repo_consequence_repo_impact_association_table',
    sa.Column('repo_consequence_id', sa.Integer(), nullable=True),
    sa.Column('repo_impact_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repo_consequence_id'], ['repo_consequence.id'], ),
    sa.ForeignKeyConstraint(['repo_impact_id'], ['repo_impact.id'], )
    )
    op.create_table('repo_risk_threat_asset_consequence',
    sa.Column('repo_asset_id', sa.Integer(), nullable=False),
    sa.Column('repo_threat_id', sa.Integer(), nullable=False),
    sa.Column('repo_response_id', sa.Integer(), nullable=False),
    sa.Column('repo_consequence_id', sa.Integer(), nullable=False),
    sa.Column('threat_occurrence', sa.Boolean(), nullable=False),
    sa.Column('prob', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repo_asset_id'], ['repo_asset.id'], ),
    sa.ForeignKeyConstraint(['repo_consequence_id'], ['repo_consequence.id'], ),
    sa.ForeignKeyConstraint(['repo_response_id'], ['repo_response.id'], ),
    sa.ForeignKeyConstraint(['repo_threat_id'], ['repo_threat.id'], ),
    sa.PrimaryKeyConstraint('repo_asset_id', 'repo_threat_id', 'repo_response_id', 'repo_consequence_id', 'threat_occurrence')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repo_risk_threat_asset_consequence')
    op.drop_table('repo_consequence_repo_impact_association_table')
    op.drop_table('repo_asset_threat_consequence_service_impact_relationship_consequence_many_to_many')
    op.drop_table('repo_risk_threat_asset_materialisation')
    op.drop_table('repo_risk_assessment_reports')
    op.drop_table('repo_control')
    op.drop_table('repo_consequence')
    op.drop_table('repo_asset_threat_consequence_service_impact_relationship_service_many_to_many')
    op.drop_table('vulnerability_report_vulnerabilities_link')
    op.drop_table('repo_utility_objective_relationship_many_to_many')
    op.drop_table('repo_risk_assessment')
    op.drop_table('repo_response')
    op.drop_table('repo_objective_impact_relationship_impact_many_to_many')
    op.drop_table('repo_materialisation')
    op.drop_table('repo_asset_threat_consequence_service_impact_relationship')
    op.drop_table('repo_asset_repo_threat_relationship')
    op.drop_table('repo_asset_repo_service_association_table')
    op.drop_table('vulnerabilities_weakness_link')
    op.drop_table('repo_utility_repo_objective_association_table')
    op.drop_table('repo_utility_objective_relationship')
    op.drop_table('repo_threat')
    op.drop_table('repo_service_repo_impact_association_table')
    op.drop_table('repo_objectives_options')
    op.drop_table('repo_objective_repo_impact_association_table')
    op.drop_table('repo_objective_impact_relationship')
    op.drop_table('repo_asset')
    op.drop_index(op.f('ix_vulnerability_report_reportId'), table_name='vulnerability_report')
    op.drop_table('vulnerability_report')
    op.drop_table('repo_utility')
    op.drop_table('repo_service')
    op.drop_table('repo_objective')
    op.drop_table('repo_net_group')
    op.drop_table('repo_impact')
    op.drop_table('repo_assets_type')
    op.drop_table('repo_asset_reputation')
    op.drop_table('repo_actor')
    op.drop_index(op.f('ix_common_weakness_enumeration_CWEId'), table_name='common_weakness_enumeration')
    op.drop_table('common_weakness_enumeration')
    op.drop_index(op.f('ix_common_vulnerabilities_and_exposures_description'), table_name='common_vulnerabilities_and_exposures')
    op.drop_index(op.f('ix_common_vulnerabilities_and_exposures_CVEId'), table_name='common_vulnerabilities_and_exposures')
    op.drop_table('common_vulnerabilities_and_exposures')
    op.drop_index(op.f('ix_common_attack_pattern_enumeration_classification_capecId'), table_name='common_attack_pattern_enumeration_classification')
    op.drop_table('common_attack_pattern_enumeration_classification')
    # ### end Alembic commands ###
